# ----------------------------------------
# Common environment
# ----------------------------------------
spring: 
  profiles.active: local

  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp

  output.ansi.enabled: always    

server.port : 80

---
# ----------------------------------------
# local
# ----------------------------------------
logging.level:
  org.springframework: ERROR
  com.kang: DEBUG

spring: 
  profiles: local
  
  devtools.livereload.enabled : true
  
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: kang
    password: kang
    driver-class-name: com.mysql.jdbc.Driver

---
# ----------------------------------------
# dev
# ----------------------------------------
logging.level:
  org.springframework: ERROR
  com.kang: DEBUG

spring: 
  profiles: dev
  
  datasource:
    platform: mysql
    url: jdbc:mysql:/localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: kang
    password: kang
    driver-class-name: com.mysql.jdbc.Driver
