# ----------------------------------------
# Common environment
# ----------------------------------------
spring: 
  profiles.active: local

  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
    contentnegotiation:
      favor-parameter: true 
      media-types: 
        xls: application/vnd.ms-ecel
              
    static-path-pattern: /asset/**
    
  resources:
    static-locations: classpath:/static/
    add-mappings: true
      
  output.ansi.enabled: always    
  


server:
  port: 80
  error.path: /error


logging.level:
  net.chndol.study.mybatissample.mapper: TRACE

---
# ----------------------------------------
# local
# ----------------------------------------
logging.level:
  org.springframework: ERROR
  com.kang: DEBUG

spring: 
  profiles: local
  
  devtools.livereload.enabled : true

    
  master:
    datasource:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
      username: kang
      password: kang
      testOnBorrow: true
      validationInterval: 34000
      validationQuery: SELECT 1
  slave:
    datasource:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
      username: kang
      password: kang
      testOnBorrow: true
      validationInterval: 34000
      validationQuery: SELECT 1

#---
## ----------------------------------------
## dev
## ----------------------------------------
#logging.level:
#  org.springframework: ERROR
#  com.kang: DEBUG
#
#spring: 
#  profiles: dev
#  
#  master.datasource:
#    platform: mysql
#    url: jdbc:mysql://localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
#    username: kang
#    password: kang
#    driver-class-name: com.mysql.jdbc.Driver
#  slave.datasource:
#    platform: mysql
#    url: jdbc:mysql://localhost:3306/kang?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
#    username: kang
#    password: kang
#    driver-class-name: com.mysql.jdbc.Driver
